const menu = [
    {
      id: 1,
      title: 'pancakes',
      category: 'breakfast',
      price: 250,
      img: 'https://cdn.pixabay.com/photo/2017/05/07/08/56/pancakes-2291908_960_720.jpg',
      desc: `A pancake is a flat cake, often thin and round, prepared from a starch-based batter that may contain eggs, milk and butter and cooked on a hot surface such as a griddle or frying pan, often frying with oil or butter.`,
    },
    {
      id: 2,
      title: 'Medium Rare Steak',
      category: 'lunch',
      price: 250,
      img: 'https://cdn.pixabay.com/photo/2017/11/10/15/04/steak-2936531_960_720.jpg',
      desc: `A steak is a meat generally sliced across the muscle fibers, potentially including a bone.It can also be cooked in sauce, such as in steak and kidney pie`,
    },
    {
      id: 3,
      title: 'Strawberry milkshake',
      category: 'shakes',
      price: 90,
      img: 'https://images.pexels.com/photos/8805097/pexels-photo-8805097.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
      desc: `A milkshake is a sweet drink made by blending milk, ice cream, Strawberry and flavorings or sweeteners`,
    },
    {
      id: 4,
      title: 'Avacado toast with fried egg',
      category: 'breakfast',
      price: 190,
      img: 'https://images.pexels.com/photos/5591718/pexels-photo-5591718.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
      desc: `Made with whole grain toast with sliced avocado, a runny egg and a few dashes of hot sauce.`,
    },
    {
      id: 5,
      title: 'Pumpkin cream soup with croutons',
      category: 'lunch',
      price: 259,
      img: 'https://images.pexels.com/photos/7218638/pexels-photo-7218638.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
      desc: `Rich and creamy pumpkin soup recipe topped with toasty grilled cheese croutons `,
    },
    {
      id: 6,
      title: 'oreo milkshake',
      category: 'shakes',
      price: 230,
      img: 'https://images.pexels.com/photos/3998764/pexels-photo-3998764.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
      desc: `A super easy milkshake made with vanilla ice cream, milk, and Oreo cookies! that can be enjoyed by anyone`,
    },
    {
      id: 7,
      title: 'Croissant and coffee',
      category: 'breakfast',
      price: 450,
      img: 'https://images.pexels.com/photos/890515/pexels-photo-890515.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
      desc: `The croissant can be stuffed with custard, Nutella and served with hot coffee `,
    },
    {
      id: 8,
      title: 'Garlic Butter Baked Salmon',
      category: 'lunch',
      price: 200,
      img: 'https://cdn.pixabay.com/photo/2014/11/05/15/57/salmon-518032_960_720.jpg',
      desc: `Salmon only needs 8-10 minutes cooking time in a hot, preheated oven (400°F or 200°C). I broil/grill ours in the last 2 minutes of cook time to get those crispy, golden charred edges. `,
    },
    {
      id: 9,
      title: 'Fried rice with poached egg,Zucchini and celery',
      category: 'lunch',
      price: 590,
      img: 'https://images.pexels.com/photos/1410235/pexels-photo-1410235.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
      desc: `Fried rice is comfort food for those of us who consider rice as a staple. Since we cook rice on a daily basis.zucchinis are great in fried rice because they are firm and easy to prepare. Zucchinis also combine well with eggs, hence this super quick and easy Zucchini and Egg Fried Rice.`,
    },
  ];
  export default menu;